logging:
  level: INFO
  loggers:
    cz.cvut.fit.project.skld.api: DEBUG

# Database settings.
database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: selvek

  # the password
  password: ""

  # the JDBC URL
  url: jdbc:postgresql:skld

server:
  type: simple
  connector:
    type: http
    port: 8080

jwtSecret: onopFMW19gwpgo5qrwdxqhPNl8jZ3X26F0isuKUhW1R+AXkzObPORHjZWt7eh7DTp1LJPBxZ5CGyELTSZAN0cA